version: "3.1"
services:
  db:
    image: mysql:8.0.24
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: DOLMA
      MYSQL_PASSWORD: ssafyc102
      MYSQL_ROOT_PASSWORD: ssafyc102
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /User/jenkinsDir/mysql-data:/var/lib/mysql
