version: "3.1"
services:
  db:
    image: mysql:8.0.22
    container_name: db
    ports:
      - "4000:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /mnt/disks/disk1/mysql-data:/var/lib/mysql
